version: '3'

services:
  redisapp:
    image: redis
  cliapp:
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redisapp
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redisapp
    ports: [6700:80]